"""Add router and transfer pin

Revision ID: 7fb0bfb24d32
Revises: b9b0bb9c2949
Create Date: 2026-06-21 18:47:52.948772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb0bfb24d32'
down_revision: Union[str, Sequence[str], None] = 'b9b0bb9c2949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('plan_id', sa.Uuid(), nullable=True))
    op.add_column('transactions', sa.Column('transfer_pin', sa.String(length=6), nullable=True))
    op.add_column('transactions', sa.Column('authorized_mac', sa.String(length=17), nullable=True))
    op.add_column('transactions', sa.Column('is_transferred', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_transactions_plan_id'), 'transactions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_transactions_transfer_pin'), 'transactions', ['transfer_pin'], unique=True)
    op.create_foreign_key(None, 'transactions', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_transfer_pin'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_plan_id'), table_name='transactions')
    op.drop_column('transactions', 'is_transferred')
    op.drop_column('transactions', 'authorized_mac')
    op.drop_column('transactions', 'transfer_pin')
    op.drop_column('transactions', 'plan_id')
    # ### end Alembic commands ###
